# Generated by Django 4.0.4 on 2022-04-24 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0003_remove_systemuser_theme'),
    ]

    operations = [
        migrations.RenameField(
            model_name='systemuser',
            old_name='first_name',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='systemuser',
            name='last_name',
        ),
    ]
