# Generated by Django 4.0.4 on 2022-04-19 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_content'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
