# Generated by Django 4.0.4 on 2022-04-19 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='chapter',
        ),
        migrations.DeleteModel(
            name='Option',
        ),
        migrations.DeleteModel(
            name='Quiz',
        ),
    ]
